on: push

jobs:
  say_hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@23b5a9f

      - name: Greeting Message
        run: echo Hello, world
